### ISSUE TITLE
Is it compatible with laravel 9.x?

### ISSUE THREAD

**Issue by jrbecart** [chrismcintosh/laravel-log-s3-driver#5]
If yes can you update the laravel requirement to:
`"laravel/framework": "^9.0|^10.0|^11.0",`

**Comment by chrismcintosh** [comment]
Hi, I'm not sure if it is or not. I'll have to try a Laravel 9 installation. If it works I'm happy to expand the compatibility rules.

**Comment by jrbecart** [comment]
I tested, monolog needs to be 2.x and there is a small change involved when using this monolog version.

Let me know if you can see the code diff from :
https://github.com/chrismcintosh/laravel-log-s3-driver/compare/main...jrbecart:laravel-log-s3-driver-l9:main

**Comment by chrismcintosh** [comment]
@jrbecart thanks so much for doing the legwork necessary here.

I see at least 2 issues here that prevent me merging this as-is.

1. The line here will need to be switched from object ($record->formatted) to array syntax ($record['formatted']) 
https://github.com/jrbecart/laravel-log-s3-driver-l9/blob/295f49e0a2cb662614a39a32d2583165b17a96e3/src/Handler.php#L44
2. In its current format this breaks compatibility with Laravel 11. I dont have any more time to test tonight but I think if you update your version to allow Monolog 2^|3^ it might help this along - or maybe might have to write for version 2 and version 3 of monolog separate (not sure yet)

Heres the error I got on a fresh laravel 11 installation when trying to install the package using this version

```
╰─ composer update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires jrbecart/laravel-log-s3-driver-l9 dev-main -> satisfiable by jrbecart/laravel-log-s3-driver-l9[dev-main].
    - Root composer.json requires pestphp/pest-plugin-laravel ^3.0 -> satisfiable by pestphp/pest-plugin-laravel[v3.0.0].
    - pestphp/pest-plugin-laravel v3.0.0 requires laravel/framework ^11.22.0 -> satisfiable by laravel/framework[v11.22.0, ..., v11.23.5].
    - laravel/framework[v11.22.0, ..., v11.23.5] require monolog/monolog ^3.0 -> satisfiable by monolog/monolog[3.0.0, ..., 3.7.0].
    - Conclusion: don't install monolog/monolog 3.7.0 (conflict analysis result)

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

Thanks for your help!

**Comment by jrbecart** [comment]
Thank you for the feedback.
This version seems to work for me, you may try it:
https://github.com/chrismcintosh/laravel-log-s3-driver/compare/main...jrbecart:laravel-log-s3-driver-l9:main

EDIT: fixed typo missing $

**Comment by chrismcintosh** [comment]
@jrbecart Hi I've tested this with both Laravel 9 and Laravel 11 and it works in both environments. If you'd like to submit a PR with the your most recent commits you submitted for testing I will merge it.

Thanks for your patience!

**Comment by jrbecart** [comment]
@chrismcintosh Thank you. Done.
#6
